# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'QuickSample' do

end

target 'QuickSampleTests' do
  pod 'Quick', '~> 0.9.1'
  pod 'Nimble', '~> 3.1.0'
end

